### ISSUE TITLE
why can't i change the hi-speed in the game

### ISSUE THREAD

**Issue by Seraph006** [wcko87/lr2oraja#1]
do you know why i am still use lr2?

i can't find any other client has the feature,i don’t want to restart the client just because I switch a song.

The beatoraja's author's brain is sick, and others,(QMS...)

**Comment by wcko87** [comment]
You can definitely change hi-speed in the game.
Refer to the guide for info: https://github.com/wcko87/beatoraja-english-guide/wiki/Scroll-Speed-and-Green-Number
